### ISSUE TITLE
App crashes when I close the app.

### ISSUE THREAD

**Issue by namelessperson0** [hhanh00/zwallet#118] opened 2023-10-28 14:16 UTC
### Issue
App is not responding when I close the app. I have to close the app by terminating the process. 
Facing the issue around 90% of the time. Issue less frequent if I close the app after stopping the sync process. 

### Environment
* version of YWallet: 1.4.3+473
* Debian 11

**Comment by hhanh00** [comment] 2023-12-20 10:21
Duplicate of #124

**Closed by hhanh00** 2023-12-20 10:21 UTC
Labels: Priority-Low
