### ISSUE TITLE
App image throws error but Flatpak works

### ISSUE THREAD

**Issue by namelessperson0** [hhanh00/zwallet#119] opened 2023-10-28 14:19 UTC
### Subject of the issue
Ywallet appimage throws below error 
`tmp/.mount_YwalleyAN6K0/ywallet: symbol lookup error: /tmp/.mount_YwalleyAN6K0/usr/lib/x86_64-linux-gnu/libgdk-3.so.0: undefined symbol: wl_proxy_marshal_flags`

The corresponding version of Ywallet in flatpak works.

### Environment
* version of YWallet: 1.4.3+473
* Debian 11

**Comment by hhanh00** [comment] 2023-10-30 13:35
Duplicate of #84

**Closed by hhanh00** 2023-10-30 13:35 UTC
